In [1]:
import numpy as np

## small samples will return constant scores, then the correlation will be nan by default
def replace_nan_with_zero(array):
    return np.nan_to_num(array)

scoring = {'agnews':'accuracy', 'trec':'accuracy', 'semeval':'accuracy', 'chemprot':'accuracy',
           'youtube':'accuracy', 'imdb':'accuracy', 'yelp':'accuracy',
           'census':'f1', 'tennis':'f1', 'sms':'f1', 'cdr':'f1', 'basketball':'f1', 
           'spouse':'f1', 'commercial':'f1'}
datasets = scoring.keys()
len(datasets)

14

In [2]:
results = np.load('../results/results_exp4.npy', allow_pickle=True).item()

In [3]:
for metric in ['corr','score']:
    print(metric)
    print(np.vstack([np.delete(np.round(np.mean(replace_nan_with_zero(np.array(results[dataset][metric])),axis=0),2), 4, 0) for dataset in datasets]))
    print('\n')
    print(np.vstack([np.delete(np.round(np.std(replace_nan_with_zero(np.array(results[dataset][metric])),axis=0),2), 4, 0) for dataset in datasets]))
    print('\n\n')

corr
[[ 0.91  0.86  0.86  0.92  0.39  0.35  0.5   0.76]
 [-0.32  0.37  0.19  0.44 -0.03 -0.06 -0.1   0.17]
 [ 0.87 -0.84  0.88  0.88  0.13  0.17  0.64  0.62]
 [ 0.75 -0.66  0.38  0.49 -0.01 -0.12 -0.02  0.06]
 [ 0.38 -0.42 -0.01  0.17  0.41  0.42  0.38  0.58]
 [ 0.84  0.76  0.71  0.92  0.17  0.4   0.61  0.65]
 [ 0.01 -0.5  -0.49 -0.31  0.08  0.09  0.14  0.45]
 [ 0.85  0.94  0.96  0.98  0.    0.    0.03  0.18]
 [ 0.83  0.74  0.8   0.9   0.33  0.41  0.51  0.52]
 [ 0.    0.99  0.99  1.    0.    0.    0.    0.  ]
 [ 0.8   0.89  0.92  0.98  0.03  0.07  0.07  0.09]
 [ 0.85  0.69  0.73  0.81  0.35  0.53  0.59  0.59]
 [ 0.53  0.86  0.86  1.    0.    0.    0.    0.1 ]
 [ 0.95  0.96  0.99  1.    0.14  0.26  0.28  0.31]]


[[0.01 0.   0.   0.01 0.31 0.54 0.53 0.19]
 [0.36 0.32 0.34 0.39 0.55 0.39 0.34 0.52]
 [0.04 0.04 0.04 0.04 0.64 0.69 0.32 0.41]
 [0.08 0.11 0.11 0.15 0.47 0.45 0.43 0.41]
 [0.21 0.19 0.21 0.29 0.35 0.27 0.31 0.19]
 [0.01 0.   0.02 0.01 0.49 0.46 0.28 0.3 ]
 [0.08 0.05 0.05 0.1